### ISSUE TITLE
代码的扩展性不是很好

### ISSUE THREAD

**Issue by Mr-lins** [runlhy/HYPageView#3]
比如 我进去要选中第二个title 而不是第一个呢。我看着HYPageView这个类里面改就出BUG了

**Comment by Mr-lins** [comment]
大神  能解答下我这个问题嘛

**Comment by runlhy** [comment]
提供了默认下标的接口，你可以参考一下。

**Comment by Mr-lins** [comment]
感谢 大神分享

**Comment by Mr-lins** [comment]
大神底部有个横条  有属性可以去掉嘛
![snip20170516_30](https://cloud.githubusercontent.com/assets/26573094/26104323/ea933a46-3a6f-11e7-8c93-a5ae9aa2fe22.png)

**Comment by Mr-lins** [comment]
@runlhy    使用中发现个问题
